# Generated by Django 3.1 on 2020-08-12 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200808_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('numero', models.IntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('cuatrimestre', models.IntegerField(choices=[(0, 'Verano'), (1, 'Primer Cuatrimestre'), (2, 'Segundo Cuatrimestre')])),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.materias')),
            ],
        ),
        migrations.CreateModel(
            name='Examenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIPO', models.CharField(choices=[('P1', 'Primer Parcial'), ('P2', 'Segundo Parcial'), ('P3', 'Tercer Parcial'), ('R1', 'Primer Recuperatorio'), ('R2', 'Segundo Recuperatorio'), ('R3', 'Tercer Recuperatorio'), ('F', 'Final')], max_length=2)),
                ('anio', models.PositiveIntegerField()),
                ('cuatrimestre', models.IntegerField(choices=[(0, 'Verano'), (1, 'Primer Cuatrimestre'), (2, 'Segundo Cuatrimestre')])),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.materias')),
            ],
        ),
        migrations.CreateModel(
            name='EjerciciosGuias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('inciso', models.CharField(blank=True, max_length=10)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.guias')),
            ],
        ),
        migrations.CreateModel(
            name='EjerciciosExamenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('inciso', models.CharField(blank=True, max_length=10)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.examenes')),
            ],
        ),
    ]
