# Generated by Django 3.1 on 2020-08-12 05:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ejerciciosexamenes_ejerciciosguias_examenes_guias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejerciciosexamenes',
            name='numero',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='ejerciciosguias',
            name='numero',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='examenes',
            name='anio',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2010), django.core.validators.MaxValueValidator(2050)]),
        ),
        migrations.AlterField(
            model_name='guias',
            name='anio',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2010), django.core.validators.MaxValueValidator(2050)]),
        ),
        migrations.AlterField(
            model_name='guias',
            name='numero',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
