# Generated by Django 3.1 on 2020-08-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200812_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenes',
            name='TIPO',
            field=models.CharField(choices=[('P1', 'Primer Parcial'), ('P2', 'Segundo Parcial'), ('R1', 'Primer Recuperatorio'), ('R2', 'Segundo Recuperatorio'), ('F', 'Final'), ('O', 'Otro')], max_length=2),
        ),
    ]
