# Generated by Django 3.1 on 2020-08-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200821_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examenes',
            old_name='TIPO',
            new_name='tipo',
        ),
    ]
